version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
  web1:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    links:
      - db
 
  web2:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    links:
      - db

  haproxy:
    build: ./haproxy
    container_name: haproxy
    ports:
      - "80:80"
